// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_paraPage;
lv_obj_t * ui_tempPanel;
lv_obj_t * ui_Image1;
lv_obj_t * ui_tempLabel;
lv_obj_t * ui_brightPanel;
lv_obj_t * ui_Image3;
lv_obj_t * ui_brightLabel;
lv_obj_t * ui_wetPanel;
lv_obj_t * ui_Image4;
lv_obj_t * ui_wetLabel;
lv_obj_t * ui_bombPanel;
lv_obj_t * ui_Image5;
lv_obj_t * ui_bombLabel;
lv_obj_t * ui_fanPanel;
lv_obj_t * ui_Image7;
lv_obj_t * ui_fanLabel;
lv_obj_t * ui_wifiPanel;
lv_obj_t * ui_Image8;
lv_obj_t * ui_wifiLabel;
lv_obj_t * ui_ipPanel;
lv_obj_t * ui_Image9;
lv_obj_t * ui_ipLabel;
lv_obj_t * ui_hotpotPanel;
lv_obj_t * ui_Image10;
lv_obj_t * ui_hotpotLabel;
lv_obj_t * ui_fresh_Label;
lv_obj_t * ui_settingPage;
lv_obj_t * ui_tempSetPanel;
lv_obj_t * ui_Label2;
void ui_event_tempSetSlider(lv_event_t * e);
lv_obj_t * ui_tempSetSlider;
lv_obj_t * ui_brightSetPanel;
lv_obj_t * ui_Label3;
void ui_event_brightSetSlider(lv_event_t * e);
lv_obj_t * ui_brightSetSlider;
lv_obj_t * ui_netSetPanel;
lv_obj_t * ui_Label6;
void ui_event_netSetBotton(lv_event_t * e);
lv_obj_t * ui_netSetBotton;
lv_obj_t * ui_aboutPage;
lv_obj_t * ui_Label7;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_tempSetSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_slider_set_text_value(ui_Label2, target, "温度：", "%");
        LVGL_set_temp(e);
    }
}
void ui_event_brightSetSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_slider_set_text_value(ui_Label3, target, "亮度：", "%");
        LVGL_set_bright(e);
    }
}
void ui_event_netSetBotton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        LVGL_set_net(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
